get_zones:
  fields:
    config_entry_id:
      required: true
      example: 1234567890abcdef1234567890abcdef
      selector:
        config_entry:
          integration: pima_force
set_zones:
  fields:
    config_entry_id:
      required: true
      example: 1234567890abcdef1234567890abcdef
      selector:
        config_entry:
          integration: pima_force
    zones:
      required: true
      example:
        - Front Door
        - ""
        - Back Door
      selector:
        object:

